In [1]:
import numpy as np
from scipy.linalg import lu_solve, lu_factor

In [2]:
# matrix_A = [[4, 2, 0], [2,3,1], [0,1,5/2]]

matrix_A = [[9.0, 3.0, 2.0, 0.0, 7.0], 
            [7.0, 6.0, 9.0, 6.0, 4.0], 
            [2.0, 7.0, 7.0, 8.0, 2.0], 
            [0.0, 9.0, 7.0, 2.0, 2.0], 
            [7.0, 3.0, 6.0, 4.0, 3.0]]

matrix_A = np.array(matrix_A, dtype=np.float64)

# matrix_b = [2,5,6]

matrix_b = [35.0, 58.0, 53.0, 37.0, 39.0]

matrix_b = np.array(matrix_b, dtype=np.float64)

In [3]:
lu, piv = lu_factor(matrix_A)
lu

array([[ 9.        ,  3.        ,  2.        ,  0.        ,  7.        ],
       [ 0.        ,  9.        ,  7.        ,  2.        ,  2.        ],
       [ 0.77777778,  0.40740741,  4.59259259,  5.18518519, -2.25925926],
       [ 0.22222222,  0.7037037 ,  0.35483871,  4.75268817, -0.16129032],
       [ 0.77777778,  0.07407407,  0.85483871, -0.12217195, -0.68099548]])

In [4]:
lu_solve((lu, piv), matrix_b)

array([1.25825276e-15, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
       4.00000000e+00])

In [5]:
indx = np.arange(0, matrix_A.shape[0])

for i in range(0, matrix_A.shape[0]-1):
    am = np.abs(matrix_A[i, i])
    p = i
    
    
    for j in range(i+1, matrix_A.shape[0]):
        if np.abs(matrix_A[j, i]) > am:
            am = np.abs(matrix_A[j, i])
            p = j
    
    if p > i:        
        for k in range(0, matrix_A.shape[0]):
            hold = matrix_A[i,k]
            matrix_A[i, k] = matrix_A[p, k]
            matrix_A[p, k] = hold
        
        ihold = indx[i]
        indx[i] = indx[p]
        indx[p] = ihold
        
    
    for j in range(i+1, matrix_A.shape[0]):
        matrix_A[j, i] = matrix_A[j, i] / matrix_A[i, i]
        
        for k in range(i+1, matrix_A.shape[0]):
            matrix_A[j, k] = matrix_A[j, k] - matrix_A[j, i] * matrix_A[i, k]
            
matrix_A

array([[ 9.        ,  3.        ,  2.        ,  0.        ,  7.        ],
       [ 0.        ,  9.        ,  7.        ,  2.        ,  2.        ],
       [ 0.77777778,  0.40740741,  4.59259259,  5.18518519, -2.25925926],
       [ 0.22222222,  0.7037037 ,  0.35483871,  4.75268817, -0.16129032],
       [ 0.77777778,  0.07407407,  0.85483871, -0.12217195, -0.68099548]])

In [6]:
matrix_b

array([35., 58., 53., 37., 39.])

In [7]:
indx

array([0, 3, 1, 2, 4])

In [8]:
x = np.zeros(matrix_A.shape[0])

for k in range(0, matrix_A.shape[0]):
    x[k] = matrix_b[indx[k]]
    
for k in range(0, matrix_A.shape[0]):
    matrix_b[k] = x[k]
    
x

array([35., 37., 58., 53., 39.])

In [9]:
matrix_b

array([35., 37., 58., 53., 39.])

In [10]:
y = np.zeros(matrix_A.shape[0])
y[0] = matrix_b[0]

for i in range(1, matrix_A.shape[0]):
    sum = 0.0
    
    for j in range(0, i):
        sum = sum + matrix_A[i, j] * y[j]
    
    y[i] = (matrix_b[i] - sum)
    
y

array([35.        , 37.        , 15.7037037 , 13.61290323, -2.7239819 ])

In [11]:
x[-1] = y[-1] / matrix_A[-1, -1]

for i in range(matrix_A.shape[0]-1, -1, -1):
    sum = 0.0
    
    for j in range(i+1, matrix_A.shape[0]):
        sum = sum + matrix_A[i, j] * x[j]
    
    x[i] = (y[i] - sum) / matrix_A[i, i]
    
x

array([-6.31593543e-15,  1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
        4.00000000e+00])